package com.ovi.analyser;

public enum AL {
	// OPEATORS
	ADD, SUB, MUL, DIV, DOT, AND, OR, NOT, ASSIGN, EQUAL, NOTEQ, LESS, LESSEQ, GREATER, GREATEREQ,

	// DEDELIMTERS
	COMMA, SEMICOLON, LPAR, RPAR, LBRACKET, RBRACKET, LACC, RACC,

	// CONSTANTS
	CT_INT, CT_REAL, CT_CHAR, CT_STRING,

	// IDENTIFIERS
	ID
}
